Update cts tests to be compatible for both art and dalvik.
- Removes tests that check that certain integral types can't be put into
  other integral types, ie. an int value of 2 put into a boolean. Dalvik
  disallows this, but art allows this. However, the instruction type must
  still match the array or field type.

- Changed how some invoke tests are run to trigger a runtime exception
  expected in art, as well as a verification error expected in dalvik.

- Changed some invoke tests to allow NoSuchMethodError expected in dalvik
  and VerifyError expected in art, with art being closer to the RI.

- Fixed various bytecodes to have proper arguments because art has
  stricter checks.

Bug: 10135051

Change-Id: I48fbf24d5f07faf23bb404685998bd358846b76b